# A sample Gemfile
if ENV['RUBYGEMS']
	source 'https://rubygems.org'
else
	source 'https://ruby.taobao.org'
end

gem 'gem-browse'
gem 'rails'
gem 'rails-i18n'
gem 'camping'
gem 'thin'
gem 'mysql2'
gem 'mechanize'
gem 'sidekiq'
gem 'devise'
gem 'thor'
gem 'carrierwave'
gem 'therubyracer'
gem 'rubyscript2exe'
gem 'pdf-stamper'
gem 'prawn'
gem 'pdf-reader'
gem 'pdftk'
gem 'rubytree'
gem 'gon'
gem 'unicorn'
gem 'irbtools'
gem 'irbtools-more'
gem 'awesome_print'
gem 'hooks'
gem 'reek'
gem 'browser'
gem 'pundit'
gem 'brakeman'
gem 'awesome_nested_set'
gem 'parallel'
gem 'savon'
gem 'auto-correct'
gem 'transmuter'
gem 'factory_girl'
gem 'factory_girl_rails'
gem 'bindata'
gem 'mongoid'
gem 'whenever'
gem 'redis-activesupport'
gem 'rack'
gem 'warden'
gem 'rspec'
gem 'kaminari'
gem 'nlpir'

group :development do
	gem "better_errors"
end
